### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by AlekSi** [hlandau/passlib#2]
I almost decided to use this library (and contribute PBKDF2). Then I found dependency on your metrics library. I like metrics too, but I don't think that hard dependency inside library (as apposed to application) is a good thing. Please consider to remove it.

**Comment by hlandau** [comment]
Out of curiosity, would you have objected to use of expvar? Because that's basically what it is.

Please see https://github.com/hlandau/measurable for my philosophy on this. Particularly important is this article: https://www.devever.net/~hl/nexuses

In particular, the registration of those metrics is not *in itself* exposed anywhere (e.g. via HTTP). Only if you did that yourself would those metrics be accessible. i.e. registration of metrics and consumption/exposure of metrics are *completely* separate in my code. This is intended to alleviate concerns exactly like yours.

I'm happy to debate this if you're not convinced by the above, in the interests of getting to a more general-purpose library.

At any rate, I'd note that stripping out the metrics code would be a very simple patch which would probably be very easy for you to maintain in a fork while tracking my codebase. This would probably be less work on your part than doing your own library, and wouldn't have much of a maintenance burden given that it's going to be rare for me to touch the metric code, so merge conflicts will be rare.
