### ISSUE TITLE
Is there a way of adding a custom salt to the hashing process?

### ISSUE THREAD

**Issue by Splizard** [hlandau/passlib#3]

**Comment by hlandau** [comment]
So you want something like a pepper value, a per-site secret salt? No, unless you prefix it to the user's password yourself, or something.

Most schemes don't provide an official way to do this. Which means you either end up mixing it into the salt or the password, somehow. Either way, you're deviating from the standards. It also means a password string `$foo$...` taken out of context might seem invalid for a given password when it's not. If you have a database full of password hashes, and you merge it with another, and they use different peppers, you don't know which uses which, because they both appear to use the same hashing scheme. So I'm wary of doing this when the modular crypt format doesn't provide a way to express that difference. I'm also skeptical about the utility of pepper in the first place...

It looks like the modular crypt scheme for Argon2 might end up supporting this sort of thing officially, so I might or might not add support when I add support for Argon2.

**Comment by Splizard** [comment]
Thanks the pepper value is what I was after :)
I would suggest documenting being able to add a pepper value in the example.

**Comment by hlandau** [comment]
Sure. If you prepend pepper, be warned that bcrypt (but not bcryptsha256) has a password length limit. Anything in excess is silently truncated. passlib won't generate bcrypt passwords by default, but I guess it could be a concern if you have existing bcrypt passwords or something. Anyway, it's probably safer to append pepper to the password string. than prepend it.

**Comment by barraponto** [comment]
Adding this link because this is one of the first results when searching for `passlib pepper`.
https://security.stackexchange.com/questions/3272/password-hashing-add-salt-pepper-or-is-salt-enough
